** MSOffice doesn't work
   https://office365.uservoice.com/forums/264636-general/suggestions/34609312-add-the-manage-rules-function-in-conditional-for
** Python on Mac
   https://opensource.com/article/19/5/python-3-default-mac

   https://docs.conda.io/en/latest/index.html

   You need this:
   https://github.com/pyenv/pyenv/issues/849
   ??
** Javascript
<2022-09-10 Sat> ESM require https://stackoverflow.com/questions/69081410/error-err-require-esm-require-of-es-module-not-supported
<2022-09-13 Tue> Modules deep dive cartoon https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/
<2022-09-13 Tue> Default exports https://bignerdranch.com/blog/default-exports-or-named-exports-why-not-both/
<2022-10-20 Thu> How promise exceptions can work https://codeburst.io/improving-your-stack-trace-when-a-promise-fails-b2a5fe9c899a
<2023-05-16 Tue> What Babel do and how https://www.youtube.com/watch?v=C2PDAGCrk_g
** ReactNative
<2023-02-15 Wed> Arm yourself: https://www.obytes.com/blog/what-you-need-to-know-about-native-developement-as-react-native-developer-part1
<2023-02-16 Thu> Android Install with debug options https://stackoverflow.com/questions/42596358/how-to-enable-stacktrace-react-native-run-android-command
<2023-02-16 Thu> Android app dependencies https://www.stkent.com/2020/02/04/listing-your-android-apps-actual-dependencies-in-2020.html
*** FX & rendering
<2022-11-30 Wed> ScrollView breaks RefreshControl on Android https://github.com/software-mansion/react-native-gesture-handler/issues/1067
<2022-12-01 Thu> Reanimated 2 example (pangesture)  https://www.youtube.com/watch?v=D-C7lLQ1oAk
<2022-12-01 Thu> Skia & ReactNative https://www.youtube.com/watch?v=pVesCl7TY8A
*** Hooks/State/Effects
Read the next 3 in this order
<2023-02-14 Tue> useCallback https://kinsta.com/blog/react-usecallback/
<2023-02-14 Tue> useEffect https://blog.logrocket.com/guide-to-react-useeffect-hook/
<2023-02-21 Tue> useEffect official https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often
<2023-02-14 Tue> Visibility sensor https://blog.logrocket.com/implementing-component-visibility-sensor-react-native/
<2023-02-22 Wed> Setter function changes? No https://stackoverflow.com/questions/57180731/react-is-usestate-s-setter-function-able-to-change
<2023-02-23 Thu> useEffect cleanup https://www.youtube.com/watch?v=KzH6YxW0zW4
<2023-02-24 Fri> TODO Useful callback example https://stackoverflow.com/questions/55045566/react-hooks-usecallback-causes-child-to-re-render
*** Performance

<2023-02-24 Fri> Good RN official docs https://reactnative.dev/docs/performance
<2023-02-21 Tue> flipper https://www.youtube.com/watch?v=bI1VEXVzNXs
<2023-02-21 Tue> Flipper memoise performance optimisation in practise https://www.youtube.com/watch?v=DXhcbMvNX04
<2023-02-21 Tue> flatlist performance https://www.youtube.com/watch?v=1l5Pn4VbnO4
<2023-02-23 Thu> Cache libary https://www.npmjs.com/package/moize/v/4.0.4
<2023-02-24 Fri> JS onject refs https://developapa.com/object-ids/
*** React native dev tools
NOTE! You must leave the browser open even when running the
standalone dev tools
https://reactnative.dev/docs/debugging#accessing-the-in-app-developer-menu
<2023-02-24 Fri> Make sure to install globally!
<2023-02-24 Fri> can't connect https://stackoverflow.com/questions/50867874/react-native-cannot-connect-to-react-devtools-using-android-simulator
*** Flipper
<2023-02-24 Fri> Failed to find globally installed React DevTools
https://stackoverflow.com/questions/73564919/react-native-flipper-react-devtools-not-working/73565093
*** Tips
<2022-12-01 Thu> CSS Great alignment answer https://stackoverflow.com/questions/32030050/how-can-you-float-right-in-react-native
<2022-12-01 Thu> CSS flex-start https://csslayout.news/whats-the-difference-between-the-alignment-values-of-start-flex-start-and-self-start/
<2023-02-17 Fri> React components to string https://www.emmanuelgautier.com/blog/react-element-render-to-string
<2023-05-11 Thu> XCode quirks https://stackoverflow.com/questions/58008775/xcode-11-simulatortrampoline-xpc-wants-to-access-files-managed-by-icloud-dri
<2023-05-11 Thu> Extra brackets https://stackoverflow.com/questions/49441758/why-do-i-need-an-extra-set-of-parentheses-for-react-setstate
<2023-06-14 Wed> Be careful about capturing state values in dependent callbacks, but not including these values in the dependencies list.
<2023-08-04 Fri> If there ISN'T a dependency list (like useSkiaTouchHandler) then need to use a useRef to avoid stale values.
*** NOTE The problem with Metro and tests
<2023-07-06 Thu> Testing react-dom/client error https://stackoverflow.com/questions/71713405/cannot-find-module-react-dom-client-from-node-modules-testing-library-react
<2023-07-10 Mon> Test renderer https://medium.com/@pshrmn/testing-react-native-components-in-node-with-react-test-renderer-cb2985402dce
<2023-07-10 Mon> react native test deps complication (metro) https://clojurians.slack.com/archives/C6N245JGG/p1612559155455800
<2023-07-10 Mon> React native without metro? https://sandeepqaops.medium.com/building-react-native-apks-without-metro-bundler-dependency-for-saucelabs-lambdatest-etc-2eb582a60fb
<2023-07-10 Mon> React native without metro? https://github.com/react-native-community/cli/issues/1191

The problem runnings tests on node without the simulator, is that when shadow generates your clojure code,
it relies on metro to see the require stubs generated and include in stuff like react native.
Without metro many of the dependencies aren't there.
You can resolve them to nil and get tests to run, but the results will likely not be correct
if rn/View and similar items are not available in your own components.

NOTE!!! That the :require of the test code must happen in your application file! Not only your
test file! If you want to use it. Otherwise Metro won't pick it up!


You need to be able to serialize the JS DOM (which you can do with dev libs), but that doesn't get you all the way.

https://github.com/dmg46664/problems/tree/main/0008_shadow_react_server

<2023-07-10 Mon> https://www.freecodecamp.org/news/testing-react-hooks/
- description of mounting.

<2023-07-11 Tue> Testing RN cljs  https://www.youtube.com/watch?v=6IYm34nDL64&t=543s
<2023-07-11 Tue> Enzyme https://github.com/enzymejs/enzyme/blob/master/docs/guides/react-native.md
<2023-07-11 Tue> Simple demonstration of RN tests in JS https://www.youtube.com/watch?v=6kM1Z5dDF-Q

<2023-07-12 Wed> React native testing library https://github.com/callstack/react-native-testing-library
*** Transparent buttons, menu items:
<2022-12-01 Thu> Unforutnatley no code https://react-native-web-uikit.storybook.trucknet.io/?path=/story/buttons-transparent-button--transparent-button
<2022-12-01 Thu> Ghost buttons https://docs.nativebase.io/button
Error: `useTheme` must be used within `NativeBaseConfigProvider`
can't mix and match with gesture
*** Bottom drawer / Action sheet

NOTE the following might be modal!!

<2022-12-01 Thu> Bottom drawer https://stackoverflow.com/questions/41265568/bottom-up-drawer-in-react-native
<2022-12-01 Thu> https://github.com/ammarahm-ed/react-native-actions-sheet
<2022-12-01 Thu> https://blog.logrocket.com/build-custom-react-native-action-sheet/
*** Reanimated
<2023-05-08 Mon> https://stackoverflow.com/questions/58577366/react-native-fontsize-animation-jaggy
<2023-05-08 Mon> Example https://www.youtube.com/watch?v=ffMQ_R2Q9pk
<2023-05-11 Thu> CLJS worklet https://github.com/roman01la/cljs-worklet
<2023-05-12 Fri> Make sure that if you use Animated.View that you aren't reverting to ReactNative.View somewhere embedded in stack.
<2023-05-25 Thu> Good example with useEffect https://www.youtube.com/watch?v=yz9E10Dq8Bg
 - Note that useEffect is simply setting a shared value ONCE given [] deps.
   This means withTimings is passed to the worklet in which it is able to be used.
<2023-06-04 Sun> Flatlist reanimated https://www.youtube.com/watch?v=3ox0R5jPb04
<2023-06-19 Mon> Gesture handler and Scrollview https://medium.com/@taitasciore/handling-pan-and-scroll-gestures-simultaneously-and-gracefully-with-gesture-handler-2-reanimated-63f0d8f72d3c
**** Working with memoised components
<2023-05-28 Sun> https://github.com/software-mansion/react-native-reanimated/issues/3224
Need to make sure that
- Confirmed that get-object-id (via weak hash technique) for useSharedValue doesn't change.
- Worklet gets the changed value with j/assoc! method of changing :value.
*** Skia ReactNative
<2023-06-21 Wed> Best practices (memoise) https://github.com/Shopify/react-native-skia/discussions/1233
<2023-06-22 Thu> Flaw with Reanimated and Skia https://github.com/Shopify/react-native-skia/discussions/1615#discussioncomment-6247439
*** Frameworks:
https://reactnative.dev/docs/button
https://docs.swmansion.com/react-native-gesture-handler/docs/
https://wix.github.io/react-native-ui-lib/docs/getting-started/setup
https://reactnativeelements.com/docs/next/components/header
https://wix.github.io/react-native-navigation/docs/before-you-start
https://reactnavigation.org/docs/getting-started

https://spin.atomicobject.com/2019/02/04/react-native-local-file-cache/
https://www.atomlab.dev/tutorials/react-native-fs
**** react-native-ui-libs tips
Notice how outlineColor is NOT in the style section but is its own style.
https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/ButtonsScreen.tsx#L120
Note theme manager
https://wix.github.io/react-native-ui-lib/docs/foundation/theme-manager
*** Testing
<2023-03-19 Sun> Integration testing https://www.youtube.com/watch?v=PIxaFbMBez0
*** iOS
    https://zameermfm.medium.com/solve-mac-ruby-issues-in-react-native-installations-355fb5800ee0
    https://stackoverflow.com/questions/68078996/pod-files-are-missing
<2023-08-16 Wed> iOS status bar isn't showing https://www.youtube.com/watch?v=n80T0s9AkRY
*** FlatList
<2023-05-31 Wed> https://betterprogramming.pub/overcoming-list-performance-problems-in-react-native-fad40d87b14f
<2023-05-31 Wed> https://stackoverflow.com/questions/49823933/react-native-flatlist-getitemlayout-with-dynamic-item-height
<2023-06-04 Sun> FlashList https://www.youtube.com/watch?v=ZnF_4xqwQBA
<2023-06-07 Wed> re-rendering flatlist https://stackoverflow.com/questions/43397803/how-to-re-render-flatlist
<2023-06-07 Wed> extraData! flatlist https://reactnative.dev/docs/flatlist#example
<2023-06-13 Tue> Second click (not that useful)  https://stackoverflow.com/questions/60353128/flatlist-not-update-immediately-after-button-clicked-react-native
<2023-06-13 Tue> List refresh (but list itself changed) https://www.youtube.com/watch?v=T15zdDPX3Do
*** Shadow / cljs
<2023-06-08 Thu> Bug in socket disconnected https://stackoverflow.com/questions/59416137/often-seeing-repl-command-timed-out-in-cider-with-shadow-cljs-and-react-native
** HTMX
<2022-11-30 Wed> Around the time I found HTMX... https://www.youtube.com/watch?v=3GObi93tjZI
<2023-05-06 Sat> https://www.youtube.com/watch?v=CWSmP3LSILo&t=228s
** CSS
<2022-11-26 Sat> https://jessicalyschik.com/til-how-to-monospace-numbers-in-fonts/
** Fn vs java
*** Jwrap - Map.map tuple2-> tuple2 workaround
*** Still no equivalent to clojure threading, especially relevant when threading jooq.
*** Map is responsible for BOTH transforming type & the arguments in map are responsible for,
    closing over laziness.
*** Getting a submap in Java based on a list of keys
*** No spec, and worse the loss of autocomplete
*** Problematic construction

                .getInputUserFile())
                .filter(inputUserFile -> x.equals(inputUserFile.getUserFileInformation().getUserNumber()))
                .orElse(List.of()).stream() //need this
                //.flatMap(Collection::stream)//errors

                .flatMap(Collection::stream)

                .map(errorItem -> Tuple.tuple(file, errorItem));
** Parsing
<2023-04-12 Wed> https://khanlou.com/2019/12/regex-vs-combinatorial-parsing/
** Machine learning
*** Huggingface
<2023-08-07 Mon> https://huggingface.co/docs/transformers/installation
<2023-08-07 Mon> 15m Huggingface transformers vid https://www.youtube.com/watch?v=QEaBAZQCtwE
<2023-08-07 Mon> https://stackoverflow.com/questions/64337550/neither-pytorch-nor-tensorflow-2-0-have-been-found-models-wont-be-available
<2023-08-07 Mon> Longer introduction to training https://www.youtube.com/watch?v=DQc2Mi7BcuI
*** OCR 
<2023-08-07 Mon> https://arxiv.org/abs/2109.10282
<2023-08-07 Mon> Writing a new solver with extended functions. Minghao Li https://www.youtube.com/watch?v=hKwyCWgZoQU
<2023-08-07 Mon> Hugging Face LayoutLMv2 Model True Inference https://www.youtube.com/watch?v=i6w9l9BI1NE
** Jooq and dynamic sql
   https://www.jooq.org/doc/3.9/manual-single-page/#dynamic-sql
   https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/

   https://blog.jooq.org/2018/11/05/how-to-use-jooqs-updatablerecord-for-crud-to-apply-a-delta/
   https://www.jooq.org/doc/latest/manual/sql-execution/crud-with-updatablerecords/simple-crud/
   https://blog.jooq.org/tag/insert-returning/

   Problems many-to-many mapping
   https://www.reddit.com/r/java/comments/28llql/joins_and_mapping_many_to_many_in_jooq/
   TODO https://dzone.com/articles/use-modelmapper-and-jooq
   TODO https://www.jooq.org/doc/latest/manual/sql-execution/fetching/lazy-fetching-with-streams/

   Nested
   https://stackoverflow.com/questions/38222957/jooq-can-i-fetch-a-join-of-two-tables-into-the-respective-pojos

   Batch updates (and the long manual)
   https://www.jooq.org/doc/3.14/manual-single-page/#batch-execution
** Liquibase
   https://www.exoplatform.com/blog/2017/10/18/how-to-modify-a-change-set-in-liquibase/

   Jooq runs and H2 instance and no liquibase postgres test container yet https://github.com/jOOQ/jOOQ/issues/6551



https://stackoverflow.com/questions/29503015/why-a-liquibase-migration-works-on-mysql-and-not-in-h2

   
   And subsequent problems after upgrading.
   https://groups.google.com/g/jooq-user/c/GNV4nFyxFHg

** Postgres
   https://www.citusdata.com/blog/2018/02/15/when-postgresql-blocks/

https://dba.stackexchange.com/questions/97216/how-to-correctly-use-postgresql-to-limit-multiple-and-or-concurrent-executions-o

https://www.2ndquadrant.com/en/blog/what-is-select-skip-locked-for-in-postgresql-9-5/

** Spring transaction management
   https://dzone.com/articles/spring-transaction-management-an-unconventional-gu
   https://stackoverflow.com/questions/11779469/how-do-i-get-the-connection-inside-of-a-spring-transaction
** Spring request params
    https://www.baeldung.com/spring-requestparam-vs-pathvariable
   https://stackoverflow.com/questions/56468760/how-to-collect-all-fields-annotated-with-requestparam-into-one-object
Abandoned   https://github.com/spring-projects/spring-framework/issues/23618
** Spring Testing & dependency injection

   https://www.tothenew.com/blog/loading-and-removing-bean-at-run-time-in-spring-application/
   #+begin_src
static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

        @Override
        public void initialize(final ConfigurableApplicationContext configurableApplicationContext) {

final DefaultSingletonBeanRegistry beanRegistry =
                    (DefaultSingletonBeanRegistry) configurableApplicationContext.getBeanFactory();
   #+end_src

   https://stackoverflow.com/questions/45659316/spring-boot-tests-cant-find-test-properties
   Spring minimal properties https://github.com/itzg/try-sb-test-properties-loading
   https://stackoverflow.com/questions/17353327/populating-spring-value-during-unit-test
   https://github.com/spring-projects/spring-framework/issues/16289
   https://stackoverflow.com/questions/13728000/value-not-resolved-when-using-propertysource-annotation-how-to-configure-prop

   org.springframework.context.support.AbstractApplicationContext#refresh

   https://docs.spring.io/spring-framework/docs/5.3.1/javadoc-api/org/springframework/context/annotation/Configuration.html

   Stack when loading a @Bean from test @Configuration
#+begin_src
	  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	  at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$355.1013334985.getObject(Unknown Source:-1)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	  - locked <0x1024> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:158)
	  at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
	  - locked <0x1025> (a java.lang.Object)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:127)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:275)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	  - locked <0x1026> (a org.springframework.test.context.cache.DefaultContextCache)
	  at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	  at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	  at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:99)
	 
#+end_src

How spring loads a MergedContextConfiguration for a test
#+begin_src
	  at org.springframework.test.context.MergedContextConfiguration.<init>(MergedContextConfiguration.java:246)
	  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:389)
	  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:291)
	  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:107)
	  at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:137)
	  at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:122)
	  at org.springframework.test.context.junit.jupiter.SpringExtension$$Lambda$272.547913624.apply(Unknown Source:-1)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore$$Lambda$273.1867832864.get(Unknown Source:-1)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:84)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:88)
	  at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:61)
	  at org.springframework.test.context.junit.jupiter.SpringExtension.getTestContextManager(SpringExtension.java:218)
	  at org.springframework.test.context.junit.jupiter.SpringExtension.beforeAll(SpringExtension.java:78)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda$267.1316443691.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$219.579456446.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$218.1335224354.invoke(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$217.1315606012.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$223.1940696900.accept(Unknown Source:-1)
#+end_src

Notice that @TestPropertySource must be on the test class (not on the configuration class) for it to show properites added when creating the MergedContextConfiguration above.
https://www.concretepage.com/spring-5/testpropertysource-example-spring-test

and the properties in the source added will show up here
#+begin_src
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:129)
	  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:299)
	  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:170)
	  at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
	  - locked <0x1041> (a java.lang.Object)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:127)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:275)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	  - locked <0x1042> (a org.springframework.test.context.cache.DefaultContextCache)
	  at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	  at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)

#+end_src

Problems with Lombok and Spring
https://stackoverflow.com/questions/52321988/best-practice-for-value-fields-lombok-and-constructor-injection

@EnableAutoConfiguration makes default autoconfiguration occur which will bring in hibenrate validators and other DI.
simplest to remove.

** GPG usage
   https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/signing-commits

   List keys
   gpg --list-secret-keys --keyid-format LONG

   Good tutorial on usage. Quite involved.
   https://github.com/lfit/itpol/blob/master/protecting-code-integrity.md

   https://security.stackexchange.com/questions/186649/gpg-masterkey-and-subkey-for-encryption-and-signature-and-default-keys

   http://bouncy-castle.1462172.n4.nabble.com/Trouble-Understanding-Key-Rings-and-Key-Ring-Collections-td4659433.html
** GPG Java
   https://github.com/justinludwig/jpgpj
** Spring authorisation
   Start with this:  https://www.youtube.com/watch?v=caCJAJC41Rk spring filters
   https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/authorization.html#el-common-built-in

   Can't exclude filters
   https://github.com/spring-projects/spring-boot/issues/5427

   Faking it
   https://engineering.pivotal.io/post/faking_oauth_sso/

   Externalising spring
   https://stackoverflow.com/questions/46057625/externalising-spring-boot-properties-when-deploying-to-docker
   
   https://stackoverflow.com/questions/44467133/spring-boot-authentication-for-integration-tests

   https://gigsterous.github.io/engineering/2017/05/18/wiremock-testing-security.html

   https://spring.io/guides/tutorials/spring-boot-oauth2/
   Section on 2 providers

https://stackoverflow.com/questions/59044876/whats-the-different-between-oauth2login-and-oauth2client-what-are-the-use-case
** Junit Jupiter test framework https://junit.org/junit5/docs/current/user-guide/
   https://www.baeldung.com/mockito-junit-5-extension
** TODO Spring 5 webclient  https://www.baeldung.com/spring-5-webclient
   But requires understanding https://www.baeldung.com/spring-webflux
** Git
See all anwers   https://softwareengineering.stackexchange.com/questions/365658/does-squashing-pull-requests-break-gits-merging-algorithm

Problems with squash and merge: https://softwareengineering.stackexchange.com/questions/365658/does-squashing-pull-requests-break-gits-merging-algorithm
https://dev.to/neshaz/when-to-use-git-reset-git-revert--git-checkout-18je#:~:text=%2D%2Dsoft%20%3A%20Tells%20Git%20to,the%20commit%20will%20be%20staged.

https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

https://gpgtools.org/
*** Replacing messages

git filter-repo --replace-message ../expressions.txt

I.e.
#32==>#BB_32
Note that the patterns run until no more, so be wary of doule replacement.

*** Changing emails in history
https://stackoverflow.com/questions/71951553/how-can-i-change-the-email-of-the-author-for-all-of-my-commits-in-my-repository

git-filter-repo

Choose brew over pip
https://github.com/newren/git-filter-repo/blob/main/INSTALL.md

https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html
"User and email based filtering"

Example https://www.youtube.com/watch?v=HV8hfmwDlPY

Inside the root of the git repo:
#+begin_src bash
      echo "New Name <dmg46664@noreply.github.com> <commit@email.com>" > ../temp.mailmap
      git filter-repo --mailmap ../temp.mailmap


      ;; On failure reinstalling worked.
      Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
  Python runtime state: core initialized
  ModuleNotFoundError: No module named 'encodings'

      python3 --version                                                                                                             master ⇡4  1 ✘  13:49:12
    Python 3.11.2
     ~/projects/samson-backup  brew remove git-filter-repo                                                                                                     master ⇡4  ✔  13:49:38
    Uninstalling /opt/homebrew/Cellar/git-filter-repo/2.38.0... (8 files, 281.5KB)

    brew install git-filter-repo
  #+end_src

https://lukasmestan.com/using-mailmap-in-git-repository/


**** Failed method using alias `change-commits`
Start with https://stackoverflow.com/questions/2919878/git-rewrite-previous-commit-usernames-and-emails
Note that the alias is a git alias, so the first command
registers it.

#+begin_src bash
  echo # How many commits
  git log --oneline | bb -i "(count *input*)"

  echo # Use this for the actual commands to go back. i.e. 48
  git change-commits GIT_AUTHOR_EMAIL "old@email.com" "new@email.com" HEAD~48..HEAD
#+end_src

If there is a backup, delete via
https://gist.github.com/schnell18/c8fbf8fcd268e0d120d2
https://stackoverflow.com/questions/7654822/remove-refs-original-heads-master-from-git-repo-after-filter-branch-tree-filte

*** Merge two repositories
https://peterbabic.dev/blog/merge-repos-using-git-filter-repo/
- What is git lfs https://git-lfs.github.com/
- basename /a/b/c/d -> d
  
but this has to allow unrelated histories.

#+begin_src bash
  git filter-repo --to-subdirector-filter projects/new-project-name
#+end_src

**** Artificially repairing unrelated histories
Brute force origin  https://stackoverflow.com/a/43009812/93074
git replace --graft https://stackoverflow.com/a/19860058/9307
**** Bitbucket doesn't support merging of unrelated histories.
But it does support pushing already merged unrelated histories
https://jira.atlassian.com/browse/BCLOUD-15952
** Optimistic locking
   https://vladmihalcea.com/how-to-fix-optimistic-locking-race-conditions-with-pessimistic-locking/
   https://blog.jooq.org/tag/pessimistic-locking/
   https://www.burnison.ca/articles/pessimistic-optimism-the-case-of-unexpected-deadlocks
   Oracle commiting?
   https://in.relation.to/2005/10/20/pop-quiz-does-connectionclose-result-in-commit-or-rollback/
** Functional Java
   https://stackoverflow.com/questions/19757300/java-8-lambda-streams-filter-by-method-with-exception
** TLS and SSL connection in Java & AWS PKI
    Overview
    https://stackoverflow.com/questions/24868820/how-to-make-tls-work-with-java
    Useful code pointed to 
    https://stackoverflow.com/questions/46527060/cacerts-jdk-or-jre
    Fuller overview of keytool. Doesn't make use of location.
    https://www.baeldung.com/keytool-intro

    https://docs.aws.amazon.com/crypto/latest/userguide/awspki-service-toplevel.html

    The different file formats
    https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file

    Some PPK format
    https://superuser.com/questions/1012868/generating-rsa-private-key-from-pgp-private-key-block

    https://www.wowza.com/docs/how-to-import-an-existing-ssl-certificate-and-private-key

    X509 -> GPG
    https://stackoverflow.com/questions/41904252/how-to-convert-x509-certificate-and-private-key-in-pem-format-to-gpg-format

    All different conversion. Great!
    - GnuPG to OpenSSL (self signed)
    http://sysmic.org/dotclear/index.php?post/2010/03/24/Convert-keys-betweens-GnuPG%2C-OpenSsh-and-OpenSSL

    11.1 Creating a TLS server certificate
    https://gnupg.org/documentation/manuals/gnupg.pdf

    Key tool problem
    https://p2p.wrox.com/book-beginning-cryptography-java/84066-how-save-public-key-keystore-using-keytool.html

    Which means BouncyCastle, unless other solution
    Alternatively a wrapper because BC is difficult
    https://github.com/neuhalje/bouncy-gpg

    Problem of configuring bouncy castle with only private key
    https://stackoverflow.com/questions/19187875/bouncycastle-openpgpg-how-to-create-a-pgp-keypair-with-two-user-ids

<2022-07-12 Tue> Creating your own certificates https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/
** WSS with certificates
<2022-07-12 Tue> https://github.com/websockets/ws/issues/1004
The above is a greate discussion showing either https wrapping
or NGINX reverse proxy.

<2022-07-12 Tue> https://www.nginx.com/blog/websocket-nginx/

<2022-07-13 Wed> https://forums.docker.com/t/setting-up-websocket-with-docker-nginx-and-react/60514
** Configuring SFTP

   https://hub.docker.com/r/atmoz/sftp
   https://stackoverflow.com/questions/17989883/the-cipher-aes256-cbc-is-required-but-it-is-not-available
   https://serverfault.com/questions/945505/convert-rsa-to-ppk-file-in-mac
** OAuth
   https://jwt.io/
   JSON Formatter extension
** Swagger Spring OpenAPI
** Testing
   https://medium.com/@jdmwood/integration-test-code-coverage-with-java-docker-jacoco-132f63e2f083
** MockServer
   https://mock-server.com/mock_server/running_mock_server.html

   #+begin_src
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
java.io.IOException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   #+end_src
Might get this from the client trying to connect. Make sure the client ignores certificate errors.
** SAML
   https://www.youtube.com/watch?v=SvppXbpv-5k
** JaxB
   https://www.vogella.com/tutorials/JAXB/article.html (and the Java 11 stuff at the bottom)
   Followed by :
   https://stackoverflow.com/questions/51916221/javax-xml-bind-jaxbexception-implementation-of-jaxb-api-has-not-been-found-on-mo
** Bacs transaction codes
   https://www.bacs.co.uk/resources/pages/glossary.aspx
** Clojure setup with Gradle & Reveal
*** Reveal   
    https://github.com/clojure-emacs/cider/issues/2927

    https://github.com/clojure-emacs/cider/blob/master/cider.el#L472

    From https://docs.cider.mx/cider/basics/middleware_setup.html
    #+begin_src clojure
      {:paths ["src" "resources"]
       :deps {org.clojure/clojure {:mvn/version "1.10.1"}
              vlaaad/reveal {:mvn/version "1.3.196"}
              }
       :aliases
       {
   ...
        :cider-clj {:extra-deps {cider/cider-nrepl {:mvn/version "0.22.4"}}
                    :main-opts ["-m" "nrepl.cmdline" "--middleware" "[\"cider.nrepl/cider-middleware\",\"vlaaad.reveal.nrepl/middleware\"]"]}

    #+end_src
*** Classpaths extract from Gradle
    https://gamlor.info/posts-output/2019-10-24-compile-java-with-clojure-deps/en/
    
   https://stackoverflow.com/questions/19299316/require-gradle-project-from-another-directory

   https://docs.diffblue.com/knowledge-base/cli/passing-classpath/

   https://insideclojure.org/2018/05/04/add-lib/

   This was pretty simple https://blog.mrhaki.com/2010/11/gradle-goodness-create-jar-artifact.html?m=1

   https://stackoverflow.com/questions/17416629/why-doesnt-gradle-include-transitive-dependencies-in-compile-runtime-classpat

   Maybe this?
   https://stackoverflow.com/questions/40897051/how-to-include-test-classes-into-shadowjar

   https://www.oreilly.com/library/view/gradle-beyond-the/9781449373801/ch04.html

   https://github.com/johnrengelman/shadow/issues/448

   https://discuss.gradle.org/t/how-to-include-dependencies-in-jar/19571/16


   #+begin_src groovy
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
task testShadowJar(type: ShadowJar) {
    classifier = 'tests-shadow'
//    manifest {
//        attributes 'Implementation-Title': '?????',
//                'Implementation-Version': '1.0',
//                'Built-By': '?????',
//                'Built-Date': new Date(),
//                'Built-JDK': System.getProperty('java.version'),
//                'Main-Class': mainClassName
//    }
    // Exclude signature files from other jars, because it messes up loading.
    exclude "META-INF/*.SF"
    exclude "META-INF/*.DSA"
    exclude "META-INF/*.RSA"
    // TODO Try and make it so that these aren't packaged and loaded directly
    // from build directory.
    from sourceSets.test.output
    from sourceSets.api.output
    from sourceSets.main.output
    // By default won't see transitive dependencies where implementation is called
    project.configurations.implementation.canBeResolved = true
    project.configurations.testImplementation.canBeResolved = true
    configurations = [project.configurations.testRuntime]
    configurations += [project.configurations.implementation]
    configurations += [project.configurations.testImplementation]
}
   #+end_src

#+begin_src groovy

task createPom  {
    doLast {
        pom {
            project {
                groupId 'sg.test.spring.web.guide'
                artifactId 'sg-web-initial'
                version '1.0.0-SNAPSHOT'

                inceptionYear '2008'
                licenses {
                    license {
                        name 'The Apache Software License, Version 2.0'
                        url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        distribution 'repo'
                    }
                }
            }
        }.writeTo("build/libs/pom.xml")
    }
}
#+end_src
   
   https://stackoverflow.com/questions/17325163/dependencies-dependency-version-is-missing-error-but-version-is-managed-in-pa

#+begin_src
daniel.gerson@OodleAdmins-MacBook-Pro bankrec-hud % clj -M:cider-clj
DEPRECATED: Libs must be qualified, change oobook-bankrec-deps => oobook-bankrec-deps/oobook-bankrec-deps (deps.edn)
Error building classpath. 10 problems were encountered while building the effective model for sg.test.spring.web.guide:sg-web-initial:1.0.0-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:aws-core:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:secretsmanager:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sns:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sqs:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jdbc:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-validation:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @

org.apache.maven.model.building.ModelBuildingException: 10 problems were encountered while building the effective model for sg.test.spring.web.guide:sg-web-initial:1.0.0-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:aws-core:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:secretsmanager:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sns:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sqs:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jdbc:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-validation:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:498)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:440)
	at org.apache.maven.model.building.DefaultModelBuilder.Build(DefaultModelBuilder.java:430)
	at clojure.tools.deps.alpha.extensions.pom$read_model.invokeStatic(pom.clj:64)
	at clojure.tools.deps.alpha.extensions.pom$read_model.invoke(pom.clj:54)
	at clojure.tools.deps.alpha.extensions.pom$read_model_file.invokeStatic(pom.clj:69)
	at clojure.tools.deps.alpha.extensions.pom$read_model_file.invoke(pom.clj:67)
	at clojure.tools.deps.alpha.extensions.pom$eval1401$fn__1403.invoke(pom.clj:105)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$children_task__785$fn__787$fn__788.invoke(alpha.clj:403)
	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__502.invoke(concurrent.clj:34)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

#+end_src

To solve this, just add versions to all exports.
And then make sure you change all <scope>test</scope> to runtime.
** Chrome
   https://flaviocopes.com/how-to-fix-chrome-rendering-issue/
** JIRA

   Wysiwyg debacle https://jira.atlassian.com/browse/JRACLOUD-72631

and temp solution:
   
   https://oodlefinance.atlassian.net/browse/XXXXX?oldIssueView=true
** IntelliJ

   Suppress warnings
   https://gist.github.com/vegaasen/157fbc6dce8545b7f12c
** Docker
<2022-11-18 Fri> logging https://www.papertrail.com/solution/tips/how-to-live-tail-docker-logs/
*** Docker compose
   Way to have multiple containers interact
   https://github.com/palantir/docker-compose-rule
*** Test containers
   https://stackoverflow.com/questions/64182352/can-testcontainers-join-existing-network
*** Alternatives
   https://www.youtube.com/watch?v=LGNEG-t96eE
   Minikube: https://minikube.sigs.k8s.io/

   Minikube author https://matt-rickard.com/docker-desktop-alternatives/
*** Docker API
API
https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate

How to add volumes
https://stackoverflow.com/questions/58902197/how-to-create-container-with-a-mount-in-docker-api

Multicontainer apps
https://docs.docker.com/get-started/07_multi_container/
** NGINX
Multiple config files?
https://stackoverflow.com/questions/22143565/which-nginx-config-file-is-enabled-etc-nginx-conf-d-default-conf-or-etc-nginx
** Mesos
   https://www.youtube.com/watch?v=fxJ7qnpFtrc

   Strangeloop
   https://www.youtube.com/watch?v=gVGZHzRjvo0

   Executor
   https://www.youtube.com/watch?v=tzaYXgnYKyQ
   https://blog.allegro.tech/2018/01/mesos_executor.html

   Aurora - Gears vs maze
   https://youtu.be/uSa6WZO_vCg?t=242
** Localstack
   https://docs.localstack.cloud/aws/apigatewayv2/
*** DynamoDB https://www.youtube.com/watch?v=AUPsH50c_p4
Helpful? https://baptiste.bouchereau.pro/tutorial/mock-aws-services-with-localstack/

- Doesn't seem to come up without a network perhaps?
  https://github.com/localstack/localstack/pull/6397
  https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html
** AWS
*** AWS tips
   Log insights query tips
   https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html

   Log pattern
   https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html

   Localstack setup
AWS_ACCESS_KEY_ID=DUMMY;AWS_SECRET_ACCESS_KEY=DUMMY;OOB_AWS_ENDPOINT_OVERRIDE=http://localhost:4566;AWS_REGION=eu-west-1;AWS_PROFILE=x
*** DynamoDB js v3
Working with items
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html
js v3 and v2
https://www.mischianti.org/2021/04/24/dynamodb-javascript-sdk-v2-v3-add-items-with-db-or-documentclient-3/
Gotchas
https://stackoverflow.com/questions/66591418/aws-nodejs-sdk-v3-dynamodb-updateitem-typeerror-cannot-read-property-0-of-u
CDK and dynamodb
https://stackoverflow.com/questions/71262057/aws-cdk-update-an-existing-dynamodb-table
Tables can't have dashes in column names... or it adds complexity and the workaround didn't
work for me.

Turns out the install size is large!
See
https://aws.amazon.com/blogs/developer/how-we-halved-the-publish-size-of-modular-aws-sdk-for-javascript-clients/
*** DynamoDB performance and tips
<2023-04-20 Thu> https://stackoverflow.com/questions/34552625/how-to-get-sub-10ms-response-times-from-aws-dynamodb
*** Uncategorised and interesting articles
    AWS CDK vs Terraform
    https://www.metosin.fi/blog/comparing-aws-cdk-and-terraform/

    Interesting comparing api gateway options
    https://blog.cloudcraft.co/comparing-api-gateways-on-aws/

    Hard limits on AWS lambda
    https://clojurians.slack.com/archives/C029PTWD3HR/p1635687805117000?thread_ts=1635685522.110600&cid=C029PTWD3HR

    AWS Autocompletion.
    https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html#cli-command-completion-linux

    
*** Installing and using CDK & SAM & Localstack & CDK local
    Getting started
    https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html
    npm install -g aws-cdk

    Your first app
    https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html
    (Skip this if dealing with existing app)
    
    Install aws-sam-cli (SAM)
    https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html
    See brew commands on page. (install takes a while)
    https://github.com/aws/aws-sam-cli

    Install Localstack
    https://docs.localstack.cloud/get-started/#localstack-cli
    Using pip as per instructions.
    After running 'localstack start' it takes a little while
    the logs to update.

    Install CDK local
    https://www.npmjs.com/package/aws-cdk-local

    Install AWS CLI
    https://formulae.brew.sh/formula/awscli
    brew install awscli

    Set up AWS account and configuring a profile.
    https://www.youtube.com/watch?v=2o6pY2DmVoo

    Install aws-local (wrapper around aws for localstack)
    https://github.com/localstack/awscli-local
    pip3 install awscli-local

    And then another long tutorial
    https://www.youtube.com/watch?v=I_ftyDeHffE

    
**** TODO Problems during brew install awscli
     https://github.com/Homebrew/homebrew-core/issues/100320
     
     #+begin_src
==> Pouring six--1.16.0_2.all.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink lib/python3.9/site-packages/six.py
Target /opt/homebrew/lib/python3.9/site-packages/six.py
already exists. You may want to remove it:
  rm '/opt/homebrew/lib/python3.9/site-packages/six.py'

To force the link and overwrite all conflicting files:
  brew link --overwrite six

To list all files that would be deleted:
  brew link --overwrite --dry-run six

Possible conflicting files are:
/opt/homebrew/lib/python3.9/site-packages/six.py
==> Summary
     #+end_src
**** DONE Unable to run cdklocal deploy or bootstrap
     CLOSED: [2022-04-28 Thu 16:24]
     This is solved by setting up an AWS and configuring a profile.
     
#+begin_src js
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at SdkProvider.resolveEnvironment (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:238:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at globEnvironmentsFromStacks (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/cxapp/environments.ts:19:20)
    at CdkToolkit.bootstrap (/opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:569:28)
    at initCommandLine (/opt/homebrew/lib/node_modules/aws-cdk/lib/cli.ts:341:12)
#+end_src
*** Lambda deployment and testing
Testing locally with localstack! Requires installation instructions in section above.
    https://www.youtube.com/watch?v=eszNbLXoaGQ

    Deploy and testing locally
#+begin_src bash
Deploy locally
sam local invoke -t cdk.out/***AwsDeployStack.template.json

cdklocal deploy
awslocal lambda invoke --function-name samsonBroker output.txt
#+end_src
**** DONE ERROR Not finding logs in localstack
     CLOSED: [2022-04-28 Thu 16:22]
     https://github.com/localstack/localstack/issues/2003
     https://stackoverflow.com/questions/55436251/aws-logs-the-specified-log-group-does-not-exist
 NOTE Error
 #+begin_src bash
   ;; Not necessary
   ;; export AWS_PROFILE=danielmarkgerson
   ;;
   
   awslocal logs tail /aws/lambda/
   
   An error occurred (ResourceNotFoundException) when calling the FilterLogEvents operation:
   The specified log group does not exist
 #+end_src

 Use the following to find the write name of the stack

 #+begin_src  bash
   awslocal logs describe-log-groups --endpoint-url http://localhost:4566
 #+end_src
*** Lambda usage & costs
<2023-04-19 Wed> https://stackoverflow.com/questions/56617442/lambda-function-taking-3-seconds-to-run-5-10-secs-warmup-each-time
<2023-04-19 Wed> Lambda costs https://news.ycombinator.com/item?id=26752223
<2023-04-19 Wed> Websocket costs https://www.reddit.com/r/aws/comments/p42wjw/cost_comparison_between_ec2_and_websocket_api/
*** Cloudformation
<2023-02-27 Mon> Great starter on cloud formation from the current timestamp https://youtu.be/GP-wknHzPpI?t=1495

<2023-02-27 Mon> Useful to see the cloudformation resource Types i.e. "AWS::ApiGatewayV2::Api"
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html
- see custom domain name documention on link above.
  
Converting between json and yaml
    https://jennapederson.com/blog/2021/5/17/flip-your-cloudformation-template-from-json-to-yaml/
    brew install cfn-flip

<2023-02-27 Mon> API gwv2 stage variables https://youtu.be/tgvw10C8w7c

<2023-02-28 Tue> Understanding deployments! (confusing) https://medium.com/@lancers/deployment-in-amazon-api-gateway-128c522c762e
*** Stages
<2023-02-28 Tue> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-stage.html
Because a stage has only one ApiId I suspect you can't have 1 stage sharing two apis.
<2023-02-28 Tue> https://medium.com/@TomKeeber/aws-api-gateways-c048cec63046

<2023-02-28 Tue> However, you CAN manually create a Websocket and Http API and create a "dev" stage in both of them! (tested via UI)

*** CDK and Apigateway

<2023-02-24 Fri> Good tutorial of CDK stack from scratch, (although recommend the Cloudformation one in preference)
https://www.youtube.com/watch?v=EVDw0sdxaec

<2023-02-24 Fri> Important limitations of API gateway
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html


<2023-02-27 Mon> See tests to get and understanding about how CDK is transformed!
https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-apigatewayv2/test/http/domain-name.test.ts
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-apigatewayv2/test/http/api.test.ts

    Reference
    https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigateway.RestApi.html

    To understand resources and methods, see root
    https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigateway.IRestApi.html

    Good tutorial
    https://bobbyhadz.com/blog/aws-cdk-api-gateway-example
    
    See bootstrap to template as alternative.
    https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html

    What is bootstrapping
    https://www.youtube.com/watch?v=peE3MEWa1eU
    
**** <2023-03-08 Wed> Api Gateway Logging! https://www.kevinwmcconnell.com/cdk/http-api-logs-with-cdk

**** DONE Invalid lambda response received: Lambda returned <class 'NoneType'> instead of dict
     CLOSED: [2022-04-30 Sat 12:49]
     Did you follow the whole tutorial in terms of setting up the api-gateway
     properly?
     
     Written answer on this issue
     https://stackoverflow.com/questions/70686822/why-is-my-aws-lambda-function-ending-before-finishing-with-no-timeout-message

     Interesting for general debugging, but not helpful in this case.
     https://fathomtech.io/blog/http-api-error-handling-for-aws-lambda-and-api-gateway/

     Same issue, but with more leads?
     https://stackoverflow.com/questions/65676155/sam-local-start-api-go-lambda-returns-502-internal-server-error-on-linux-ubunt
*** Bootstrapping CDK

Once per environment, there is a need for bootstrapping
https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html

To see profile use
#+begin_src bash
  aws configure list
  echo $AWS_PROFILE
  export AWS_PROFILE=yourusername
#+end_src


#+begin_src bash
  cdk synth
  cdk bootstrap aws://<amazon-id>:eu-west-2
#+end_src

**** DONE Failed access denied.
CLOSED: [2022-06-01 Wed 13:35]

#+begin_src bash
failed bootstrapping: AccessDenied: User: xxx
is not authorized to perform: cloudformation:DescribeStacks on resource:
yyy
because no identity-based policy allows the cloudformation:DescribeStacks action
#+end_src

Question
https://stackoverflow.com/questions/34237218/user-is-not-authorized-to-perform-cloudformationcreatestack
Answer
https://stackoverflow.com/a/45447236/93074

#+begin_src bash
  User: arn:aws:iam::yyy:user/dmg-access is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:eu-west-2:yyy:stack/CDKToolkit/* because no identity-based policy allows the cloudformation:DescribeStacks action
#+end_src

So we go through the process of adding permissions...

#+begin_src json
  {
            "Sid": "Stmt1449904348000",
            "Effect": "Allow",
            "Action": [
                "cloudformation:CreateStack",
                "cloudformation:CreateChangeSet",
                "cloudformation:ListStacks",
                "cloudformation:UpdateStack",
                "cloudformation:DescribeChangeSet",
                "cloudformation:ExecuteChangeSet",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DeleteStack",
                "cloudformation:GetTemplate",
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:ListAllMyBuckets",
                "s3:GetEncryptionConfiguration",
                "s3:PutEncryptionConfiguration",
                "s3:PutBucketVersioning",
                "s3:PutBucketPublicAccessBlock",
                "s3:GetBucketPolicy",
                "s3:PutBucketPolicy",
                "s3:DeleteBucketPolicy",
                "iam:GetRole",
                "iam:CreateRole",
                "ssm:PutParameter",
                "ssm:GetParameter",
                "ssm:GetParameters",
                "iam:DeleteRole",
                "iam:DeleteRolePolicy",
                "iam:DetachRolePolicy",
                "iam:AttachRolePolicy",
                "iam:PutRolePolicy",
                "ssm:DeleteParameter",
                "ecr:CreateRepository",
                "ecr:ReplicateImage",
                "ecr:DeleteRepository",
                "ecr:SetRepositoryPolicy",
                "ecr:DescribeRepositories",
                
                "dynamodb:CreateTable"
            ],
            "Resource": [
                "*"
            ]
        }
#+end_src

#+begin_src bash
02:40:10 | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket
cdk-hnb659fds-assets-245271526359-eu-west-2 already exist
#+end_src
https://serverfault.com/questions/899704/aws-s3-bucket-name-already-exists
https://github.com/aws/aws-cdk/issues/986

Delete cloud formation stack from AWS console.
5 
#+begin_src bash
  aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE

  aws cloudformation delete-stack --stack-name my-stack

  aws s3api list-buckets --query "Buckets[].Name"
#+end_src

https://docs.aws.amazon.com/cli/latest/reference/s3api/list-buckets.html

https://stackoverflow.com/questions/62972959/aws-cdk-error-bucket-policy-already-exists-on-bucket

More issues for
#+begin_src bash
    15:31:44 | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket
  API: s3:PutPublicAccessBlock Access Denied
  Environment xxx failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: API: s3:PutPublicAccessBlock Access Denied
    at prepareAndExecuteChangeSet (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:385:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:575:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:572:5)
#+end_src

Solution here:
https://stackoverflow.com/questions/53346275/amazon-s3-bucket-policy-public-access-denied
Example at bottom CLI:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3control/put-public-access-block.html

The following didn't work, ended up using the user interface console:
#+begin_src bash
  aws s3control put-public-access-block --public-access-block-configuration '{"BlockPublicAcls": true, "IgnorePublicAcls": true, "BlockPublicPolicy": true, "RestrictPublicBuckets": true}'
#+end_src

https://github.com/aws/aws-cdk/issues/17177
https://github.com/aws/aws-cdk/issues/5028
https://github.com/aws/aws-cdk/issues/8724
https://github.com/aws/aws-cdk/commit/2596ef7a99c8eeba79609d60144842f5d33fdf9b

Maybe delete the stack? Not the same error message.
https://ketuma.com/blog/cdk-bootstrap-error-and-how-to-fix-it/
However when I look on Cloudformation, there is no stack (probably rolled back).

Interesting? TODO Tried understanding what was written but unfruitful so far.
https://stackoverflow.com/questions/43033730/how-do-i-debug-an-s3createbucket-access-denied-from-cloudformation
- Can't find Managed... in my case.

Looking at stacktrace.
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/deploy-stack.ts#L385
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/cdk-toolkit.ts#L572

Informative
https://github.com/localstack/aws-cdk-local/issues/36

It was incredibly helpful to run verbose
#+begin_src
  cdk -v ....
#+end_src

Perhaps it's the following problem?? The only confusing bit is if it was this, why when I added
additional permissions to the one policy I am using did it progress further?
Not obvious...
#+begin_src
  Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
#+end_src
Nope, this didn't work.

Also in the console of the policy editor:
#+begin_src
  Ln 20, Col 16Invalid Action: The action s3:SetBucketEncryption does not exist. Learn more 
  Ln 24, Col 16Invalid Action: The action s3:PutPublicAccessBlock does not exist. Learn more 
#+end_src

This might be the answer!!!!
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutPublicAccessBlock.html
#+begin_src
  To use this operation, you must have the s3:PutBucketPublicAccessBlock permission.
#+end_src
even though the error is `StagingBucket API: s3:PutPublicAccessBlock Access Denied`

PAY ATTENTION TO THE ERROR MESSAGES IN THE POLICY EDITOR!

**** DONE Problems: No credentials.
CLOSED: [2022-05-21 Sat 17:26]

Just need to set AWS_PROFILE

#+begin_src
  Environment aws://.../eu-west-2 failed bootstrapping: Error: Need to perform AWS calls for account ..., but no credentials have been configured
    at SdkProvider.forEnvironment (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:179:46)
    at Function.lookup (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts:31:18)
#+end_src

https://github.com/aws/aws-cdk/issues/6947

... but in my case there is a generated file in there with `aws_access_key_id` and `aws_secret_access_key`.

??? https://aws.amazon.com/blogs/devops/cdk-credential-plugin/
*** CDK tips/stages
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-stages.html
<2023-02-24 Fri> programmatic stages https://stackoverflow.com/questions/62449187/deploy-multiple-api-gateway-stages-with-aws-cdk
<2023-02-24 Fri> Things to think about https://repost.aws/questions/QUAH1opLNSQVWFFnKpF-1ZTQ/the-problem-of-updating-the-apigateway-stage-in-aws-cdk
<2023-02-24 Fri> Using existing stages https://stackoverflow.com/questions/63950199/how-to-use-an-existing-stage-in-api-gateway-deployments-in-aws-cdk/64369331#64369331
<2023-02-25 Sat> Problems with Apigateway deployment design https://stackoverflow.com/questions/61027859/conflictexception-stage-already-exist-from-aws-api-gateway-deployment-with-stag
*** Websockets and api-gateway & CDK

    websocket, apigatewayv2 & CDK but NOTE v1 !!!
    https://aws.plainenglish.io/setup-api-gateway-websocket-api-with-cdk-c1e58cf3d2be

    Good chat app example
    ref  CDK https://github.com/aws-samples/multi-region-websocket-api/blob/main/cdk/lib/websockets-blog-stack.ts
    ref message https://github.com/aws-samples/multi-region-websocket-api/blob/main/src/lambda/websocket-response-handler.ts
    and original blog https://aws.amazon.com/blogs/compute/building-serverless-multi-region-websocket-apis/
    - You'll need:
      yarn add aws-sdk
      postToConnection https://stackoverflow.com/questions/56522631/aws-apigatewaymanagementapi-posttoconnection-is-not-working
      
For cljs https://dev.to/etolbakov/nbb-and-lambda-function-url-turn-a-boring-task-into-a-piece-of-cake-5294

    yarn add ApiGatewayManagementApi not ApiGatewayV2Client.
    v3 https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apigatewaymanagementapi/index.html
    v2 https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayManagementApi.html

    ApiGatewayV2Client is for in the browser, not the backend.
    https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apigatewayv2/index.html

    Still not working?
    forum: https://forum.serverless.com/t/websocket-posttoconnection-fails-with-403/13966/2

    Permissions in CDK
    https://bobbyhadz.com/blog/aws-cdk-add-lambda-permission
    Official
    https://docs.aws.amazon.com/cdk/v2/guide/permissions.html


    
    Useful? Running v2 of api-gateway
    https://stackoverflow.com/questions/69351133/aws-sam-local-api-call-to-return-version-2-of-the-event

    Stages and websockets
    https://docs.aws.amazon.com/apigateway/latest/developerguide/websocket-api-stages.html

    See next section how to connect.    
    
**** Serverless
    websockets with api gateway (Serverless API)
    https://tsh.io/blog/implementing-websocket-with-aws-lambda-and-api-gateway/


**** CDK
    CDK setup for api-gateway. Clear example.
    https://eventbus-cdk.workshop.aws/en/04-api-gateway-service-integrations/02-websocket-api/websocket-apis.html
    and references video https://www.youtube.com/watch?v=9As_ZIjUGmY

   v2 In aws-cdk, not aws-cdk-lib ... why?
    https://docs.aws.amazon.com/cdk/api/v2/docs/aws-apigatewayv2-alpha-readme.html
    installation instructions
    https://www.npmjs.com/package/@aws-cdk/aws-apigatewayv2


    Get on the right version between the two libraries.
    #+begin_src bash
      npm install aws-cdk-lib@"2.22.0"
      npm i @aws-cdk/aws-apigatewayv2-alpha
      npm i @aws-cdk/aws-apigatewayv2-integrations-alpha
    #+end_src
*** Websockets official guides & references
    
    Official AWS dev guidelines
    https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html
    See all subsections! About, Develop, Publish...


    Invoke and use wscat to test endpoint:
    https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-wscat.html
    How to connect and @connections
    https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html


    "template reference" or what's in the payload.
    https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html
    
    
*** Lambda comparison methods, further reading/viewing

Comparison
https://sanderknape.com/2018/02/comparing-aws-sam-with-serverless-framework/#:~:text=The%20biggest%20difference%20is%20that,creating%20a%20serverless%20HTTP%20endpoint.


*** SAM

    sam local start-api
    https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-start-api.html
    command reference and what happens behind the scenes.
    https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-api.html
    Understanding API gateway lambda integrations
    https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-create-api-as-simple-proxy
    

    SAM example and deployment
    https://youtu.be/MipjLaTp5nA?t=424
    - Understanding templates for type AWS::Serverless::Function lambdas (good description of considerations)
    

    Lambdas and SAM testing
    https://www.youtube.com/watch?v=AUQRyl1SNcU
    - sam local invoke -e
    - ApiGatewayFunction
    - docker in the background but this tutorial is only command line invoked.

    SAM with localstack
    https://stackoverflow.com/questions/60077552/how-to-deploy-sam-stack-with-localstack

    and SAM on same localstack network
    https://dev.to/vikasgarghb/sam-local-with-localstack-4285
    https://github.com/bilzard/aws-sam-localstack-example

    
   5 use cases
   https://www.youtube.com/watch?v=K-nnzpgrzwM
    
**** TODO Doesn't work with websockets
     https://github.com/aws/aws-sam-cli/issues/896

     Workaround:
     https://github.com/JamesKyburz/aws-lambda-ws-server

     Or:
     https://www.serverless.com/blog/api-gateway-websockets-example
     Or:
     https://onexlab-io.medium.com/serverless-localstack-lambda-53fd8d46983
     Create a doctor image for localstack https://youtu.be/BroSSrwQWKM?t=163

     SERVERLESS doesn't support localstack websockets. See bottom:
     https://github.com/localstack/serverless-localstack/issues/82


     Run serverless
     https://github.com/vendia/serverless-express
     
*** Testing

Localstack.

Faking JS sdk https://dev.to/goodidea/how-to-fake-aws-locally-with-localstack-27me
*** Serverless Framework (Alternative to CDK and cloudformation?)
    
    NPM https://www.npmjs.com/package/serverless-offline
    Github https://github.com/dherault/serverless-offline
    Tutorial https://www.youtube.com/watch?v=ul_85jfM0oo
    Youtube https://www.youtube.com/watch?v=dMVfqCTzuwk
** Browser automation
<2022-05-28 Sat> https://blog.logrocket.com/playwright-vs-puppeteer/
<2022-07-20 Wed> Playwrite vs Webdriver https://medium.com/slalom-build/playwright-vs-webdriver-the-future-of-browser-automation-854a7ae63218
*** Playwright
<2022-05-30 Mon> Remember to call .count on locators to assess number of matches.
<2022-05-30 Mon> Pay close attention to logging while using locators.
<2022-05-30 Mon> In clojure `defp` nbb macro should return type in question.
<2022-11-01 Tue> https://www.scrapingbee.com/blog/playwright-web-scraping/
<2022-11-01 Tue> https://blog.angang.ca/posts/2021/notes-playwright-go/
*** Etaoin  https://github.com/clj-commons/etaoin/blob/master/doc/01-user-guide.adoc
** Interesting stacks/services/tools
*** Silverblue
<2022-05-07 Sat> https://clojurians.slack.com/archives/C0PME9N9X/p1605895058020800

https://www.redhat.com/sysadmin/beginners-guide-silverblue
*** Getstream.io
https://getstream.io/chat/docs/react-native/querying_channels/
*** <2023-05-05 Fri> https://bitrise.io/
** Software principles / Ideas / Use cases
<2022-05-30 Mon> John Carmack QuakeCon 2012 Social interactions https://youtu.be/wt-iVFxgFWk?t=1929
<2022-10-30 Sun> Deterministic simulation https://www.youtube.com/watch?v=4fFDFbi3toc
<2022-10-30 Sun> Loom & DBs? https://jbaker.io/2022/05/09/project-loom-for-distributed-systems/
** Learning software tutorials
<2023-03-06 Mon> https://www.leshenko.net/p/ugit/#
