** MSOffice doesn't work
   https://office365.uservoice.com/forums/264636-general/suggestions/34609312-add-the-manage-rules-function-in-conditional-for
** Python on Mac
   https://opensource.com/article/19/5/python-3-default-mac

   https://docs.conda.io/en/latest/index.html

   You need this:
   https://github.com/pyenv/pyenv/issues/849
   ??
** Fn vs java
*** Jwrap - Map.map tuple2-> tuple2 workaround
*** Still no equivalent to clojure threading, especially relevant when threading jooq.
*** Map is responsible for BOTH transforming type & the arguments in map are responsible for,
    closing over laziness.
*** Getting a submap in Java based on a list of keys
*** No spec, and worse the loss of autocomplete
*** Problematic construction

                .getInputUserFile())
                .filter(inputUserFile -> x.equals(inputUserFile.getUserFileInformation().getUserNumber()))
                .orElse(List.of()).stream() //need this
                //.flatMap(Collection::stream)//errors

                .flatMap(Collection::stream)

                .map(errorItem -> Tuple.tuple(file, errorItem));


** Jooq and dynamic sql
   https://www.jooq.org/doc/3.9/manual-single-page/#dynamic-sql
   https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/

   https://blog.jooq.org/2018/11/05/how-to-use-jooqs-updatablerecord-for-crud-to-apply-a-delta/
   https://www.jooq.org/doc/latest/manual/sql-execution/crud-with-updatablerecords/simple-crud/
   https://blog.jooq.org/tag/insert-returning/

   Problems many-to-many mapping
   https://www.reddit.com/r/java/comments/28llql/joins_and_mapping_many_to_many_in_jooq/
   TODO https://dzone.com/articles/use-modelmapper-and-jooq
   TODO https://www.jooq.org/doc/latest/manual/sql-execution/fetching/lazy-fetching-with-streams/

   Nested
   https://stackoverflow.com/questions/38222957/jooq-can-i-fetch-a-join-of-two-tables-into-the-respective-pojos

   Batch updates (and the long manual)
   https://www.jooq.org/doc/3.14/manual-single-page/#batch-execution
** Liquibase
   https://www.exoplatform.com/blog/2017/10/18/how-to-modify-a-change-set-in-liquibase/

   Jooq runs and H2 instance and no liquibase postgres test container yet https://github.com/jOOQ/jOOQ/issues/6551



https://stackoverflow.com/questions/29503015/why-a-liquibase-migration-works-on-mysql-and-not-in-h2

   
   And subsequent problems after upgrading.
   https://groups.google.com/g/jooq-user/c/GNV4nFyxFHg

** Postgres
   https://www.citusdata.com/blog/2018/02/15/when-postgresql-blocks/

https://dba.stackexchange.com/questions/97216/how-to-correctly-use-postgresql-to-limit-multiple-and-or-concurrent-executions-o

https://www.2ndquadrant.com/en/blog/what-is-select-skip-locked-for-in-postgresql-9-5/

** Spring transaction management
   https://dzone.com/articles/spring-transaction-management-an-unconventional-gu
   https://stackoverflow.com/questions/11779469/how-do-i-get-the-connection-inside-of-a-spring-transaction
** Spring request params
    https://www.baeldung.com/spring-requestparam-vs-pathvariable
   https://stackoverflow.com/questions/56468760/how-to-collect-all-fields-annotated-with-requestparam-into-one-object
Abandoned   https://github.com/spring-projects/spring-framework/issues/23618
** Spring Testing & dependency injection

   https://www.tothenew.com/blog/loading-and-removing-bean-at-run-time-in-spring-application/
   #+begin_src
static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

        @Override
        public void initialize(final ConfigurableApplicationContext configurableApplicationContext) {

final DefaultSingletonBeanRegistry beanRegistry =
                    (DefaultSingletonBeanRegistry) configurableApplicationContext.getBeanFactory();
   #+end_src

   https://stackoverflow.com/questions/45659316/spring-boot-tests-cant-find-test-properties
   Spring minimal properties https://github.com/itzg/try-sb-test-properties-loading
   https://stackoverflow.com/questions/17353327/populating-spring-value-during-unit-test
   https://github.com/spring-projects/spring-framework/issues/16289
   https://stackoverflow.com/questions/13728000/value-not-resolved-when-using-propertysource-annotation-how-to-configure-prop

   org.springframework.context.support.AbstractApplicationContext#refresh

   https://docs.spring.io/spring-framework/docs/5.3.1/javadoc-api/org/springframework/context/annotation/Configuration.html

   Stack when loading a @Bean from test @Configuration
#+begin_src
	  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	  at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$355.1013334985.getObject(Unknown Source:-1)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	  - locked <0x1024> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:158)
	  at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
	  - locked <0x1025> (a java.lang.Object)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:127)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:275)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	  - locked <0x1026> (a org.springframework.test.context.cache.DefaultContextCache)
	  at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	  at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	  at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:99)
	 
#+end_src

How spring loads a MergedContextConfiguration for a test
#+begin_src
	  at org.springframework.test.context.MergedContextConfiguration.<init>(MergedContextConfiguration.java:246)
	  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:389)
	  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:291)
	  at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:107)
	  at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:137)
	  at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:122)
	  at org.springframework.test.context.junit.jupiter.SpringExtension$$Lambda$272.547913624.apply(Unknown Source:-1)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:81)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore$$Lambda$273.1867832864.get(Unknown Source:-1)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:182)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:84)
	  at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:88)
	  at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:61)
	  at org.springframework.test.context.junit.jupiter.SpringExtension.getTestContextManager(SpringExtension.java:218)
	  at org.springframework.test.context.junit.jupiter.SpringExtension.beforeAll(SpringExtension.java:78)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda$267.1316443691.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	  at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$219.579456446.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$218.1335224354.invoke(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$217.1315606012.execute(Unknown Source:-1)
	  at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	  at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	  at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$223.1940696900.accept(Unknown Source:-1)
#+end_src

Notice that @TestPropertySource must be on the test class (not on the configuration class) for it to show properites added when creating the MergedContextConfiguration above.
https://www.concretepage.com/spring-5/testpropertysource-example-spring-test

and the properties in the source added will show up here
#+begin_src
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:129)
	  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:299)
	  at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:170)
	  at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
	  - locked <0x1041> (a java.lang.Object)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:127)
	  at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:275)
	  at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	  - locked <0x1042> (a org.springframework.test.context.cache.DefaultContextCache)
	  at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	  at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	  at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)

#+end_src

Problems with Lombok and Spring
https://stackoverflow.com/questions/52321988/best-practice-for-value-fields-lombok-and-constructor-injection

@EnableAutoConfiguration makes default autoconfiguration occur which will bring in hibenrate validators and other DI.
simplest to remove.

** GPG usage
   https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/signing-commits

   List keys
   gpg --list-secret-keys --keyid-format LONG

   Good tutorial on usage. Quite involved.
   https://github.com/lfit/itpol/blob/master/protecting-code-integrity.md

   https://security.stackexchange.com/questions/186649/gpg-masterkey-and-subkey-for-encryption-and-signature-and-default-keys

   http://bouncy-castle.1462172.n4.nabble.com/Trouble-Understanding-Key-Rings-and-Key-Ring-Collections-td4659433.html
** GPG Java
   https://github.com/justinludwig/jpgpj
** Spring authorisation
   Start with this:  https://www.youtube.com/watch?v=caCJAJC41Rk spring filters
   https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/authorization.html#el-common-built-in

   Can't exclude filters
   https://github.com/spring-projects/spring-boot/issues/5427

   Faking it
   https://engineering.pivotal.io/post/faking_oauth_sso/

   Externalising spring
   https://stackoverflow.com/questions/46057625/externalising-spring-boot-properties-when-deploying-to-docker
   
   https://stackoverflow.com/questions/44467133/spring-boot-authentication-for-integration-tests

   https://gigsterous.github.io/engineering/2017/05/18/wiremock-testing-security.html

   https://spring.io/guides/tutorials/spring-boot-oauth2/
   Section on 2 providers

https://stackoverflow.com/questions/59044876/whats-the-different-between-oauth2login-and-oauth2client-what-are-the-use-case
** Junit Jupiter test framework https://junit.org/junit5/docs/current/user-guide/
   https://www.baeldung.com/mockito-junit-5-extension
** TODO Spring 5 webclient  https://www.baeldung.com/spring-5-webclient
   But requires understanding https://www.baeldung.com/spring-webflux
** Git
See all anwers   https://softwareengineering.stackexchange.com/questions/365658/does-squashing-pull-requests-break-gits-merging-algorithm

Problems with squash and merge: https://softwareengineering.stackexchange.com/questions/365658/does-squashing-pull-requests-break-gits-merging-algorithm
https://dev.to/neshaz/when-to-use-git-reset-git-revert--git-checkout-18je#:~:text=%2D%2Dsoft%20%3A%20Tells%20Git%20to,the%20commit%20will%20be%20staged.

https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

https://gpgtools.org/
** Optimistic locking
   https://vladmihalcea.com/how-to-fix-optimistic-locking-race-conditions-with-pessimistic-locking/
   https://blog.jooq.org/tag/pessimistic-locking/
   https://www.burnison.ca/articles/pessimistic-optimism-the-case-of-unexpected-deadlocks
   Oracle commiting?
   https://in.relation.to/2005/10/20/pop-quiz-does-connectionclose-result-in-commit-or-rollback/
** Functional Java
   https://stackoverflow.com/questions/19757300/java-8-lambda-streams-filter-by-method-with-exception
** TLS and SSL connection in Java & AWS PKI
    Overview
    https://stackoverflow.com/questions/24868820/how-to-make-tls-work-with-java
    Useful code pointed to 
    https://stackoverflow.com/questions/46527060/cacerts-jdk-or-jre
    Fuller overview of keytool. Doesn't make use of location.
    https://www.baeldung.com/keytool-intro

    https://docs.aws.amazon.com/crypto/latest/userguide/awspki-service-toplevel.html

    The different file formats
    https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file

    Some PPK format
    https://superuser.com/questions/1012868/generating-rsa-private-key-from-pgp-private-key-block

    https://www.wowza.com/docs/how-to-import-an-existing-ssl-certificate-and-private-key

    X509 -> GPG
    https://stackoverflow.com/questions/41904252/how-to-convert-x509-certificate-and-private-key-in-pem-format-to-gpg-format

    All different conversion. Great!
    - GnuPG to OpenSSL (self signed)
    http://sysmic.org/dotclear/index.php?post/2010/03/24/Convert-keys-betweens-GnuPG%2C-OpenSsh-and-OpenSSL

    11.1 Creating a TLS server certificate
    https://gnupg.org/documentation/manuals/gnupg.pdf

    Key tool problem
    https://p2p.wrox.com/book-beginning-cryptography-java/84066-how-save-public-key-keystore-using-keytool.html

    Which means BouncyCastle, unless other solution
    Alternatively a wrapper because BC is difficult
    https://github.com/neuhalje/bouncy-gpg

    Problem of configuring bouncy castle with only private key
    https://stackoverflow.com/questions/19187875/bouncycastle-openpgpg-how-to-create-a-pgp-keypair-with-two-user-ids
** Configuring SFTP

   https://hub.docker.com/r/atmoz/sftp
   https://stackoverflow.com/questions/17989883/the-cipher-aes256-cbc-is-required-but-it-is-not-available
   https://serverfault.com/questions/945505/convert-rsa-to-ppk-file-in-mac
** OAuth
   https://jwt.io/
   JSON Formatter extension
** Swagger Spring OpenAPI
** Testing
   https://medium.com/@jdmwood/integration-test-code-coverage-with-java-docker-jacoco-132f63e2f083
** MockServer
   https://mock-server.com/mock_server/running_mock_server.html

   #+begin_src
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
java.io.IOException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   #+end_src
Might get this from the client trying to connect. Make sure the client ignores certificate errors.
** SAML
   https://www.youtube.com/watch?v=SvppXbpv-5k
** JaxB
   https://www.vogella.com/tutorials/JAXB/article.html (and the Java 11 stuff at the bottom)
   Followed by :
   https://stackoverflow.com/questions/51916221/javax-xml-bind-jaxbexception-implementation-of-jaxb-api-has-not-been-found-on-mo
** Bacs transaction codes
   https://www.bacs.co.uk/resources/pages/glossary.aspx
** Clojure setup with Gradle & Reveal
*** Reveal   
    https://github.com/clojure-emacs/cider/issues/2927

    https://github.com/clojure-emacs/cider/blob/master/cider.el#L472

    From https://docs.cider.mx/cider/basics/middleware_setup.html
    #+begin_src clojure
      {:paths ["src" "resources"]
       :deps {org.clojure/clojure {:mvn/version "1.10.1"}
              vlaaad/reveal {:mvn/version "1.3.196"}
              }
       :aliases
       {
   ...
        :cider-clj {:extra-deps {cider/cider-nrepl {:mvn/version "0.22.4"}}
                    :main-opts ["-m" "nrepl.cmdline" "--middleware" "[\"cider.nrepl/cider-middleware\",\"vlaaad.reveal.nrepl/middleware\"]"]}

    #+end_src
*** Classpaths extract from Gradle
    https://gamlor.info/posts-output/2019-10-24-compile-java-with-clojure-deps/en/
    
   https://stackoverflow.com/questions/19299316/require-gradle-project-from-another-directory

   https://docs.diffblue.com/knowledge-base/cli/passing-classpath/

   https://insideclojure.org/2018/05/04/add-lib/

   This was pretty simple https://blog.mrhaki.com/2010/11/gradle-goodness-create-jar-artifact.html?m=1

   https://stackoverflow.com/questions/17416629/why-doesnt-gradle-include-transitive-dependencies-in-compile-runtime-classpat

   Maybe this?
   https://stackoverflow.com/questions/40897051/how-to-include-test-classes-into-shadowjar

   https://www.oreilly.com/library/view/gradle-beyond-the/9781449373801/ch04.html

   https://github.com/johnrengelman/shadow/issues/448

   https://discuss.gradle.org/t/how-to-include-dependencies-in-jar/19571/16


   #+begin_src groovy
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
task testShadowJar(type: ShadowJar) {
    classifier = 'tests-shadow'
//    manifest {
//        attributes 'Implementation-Title': '?????',
//                'Implementation-Version': '1.0',
//                'Built-By': '?????',
//                'Built-Date': new Date(),
//                'Built-JDK': System.getProperty('java.version'),
//                'Main-Class': mainClassName
//    }
    // Exclude signature files from other jars, because it messes up loading.
    exclude "META-INF/*.SF"
    exclude "META-INF/*.DSA"
    exclude "META-INF/*.RSA"
    // TODO Try and make it so that these aren't packaged and loaded directly
    // from build directory.
    from sourceSets.test.output
    from sourceSets.api.output
    from sourceSets.main.output
    // By default won't see transitive dependencies where implementation is called
    project.configurations.implementation.canBeResolved = true
    project.configurations.testImplementation.canBeResolved = true
    configurations = [project.configurations.testRuntime]
    configurations += [project.configurations.implementation]
    configurations += [project.configurations.testImplementation]
}
   #+end_src

#+begin_src groovy

task createPom  {
    doLast {
        pom {
            project {
                groupId 'sg.test.spring.web.guide'
                artifactId 'sg-web-initial'
                version '1.0.0-SNAPSHOT'

                inceptionYear '2008'
                licenses {
                    license {
                        name 'The Apache Software License, Version 2.0'
                        url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        distribution 'repo'
                    }
                }
            }
        }.writeTo("build/libs/pom.xml")
    }
}
#+end_src
   
   https://stackoverflow.com/questions/17325163/dependencies-dependency-version-is-missing-error-but-version-is-managed-in-pa

#+begin_src
daniel.gerson@OodleAdmins-MacBook-Pro bankrec-hud % clj -M:cider-clj
DEPRECATED: Libs must be qualified, change oobook-bankrec-deps => oobook-bankrec-deps/oobook-bankrec-deps (deps.edn)
Error building classpath. 10 problems were encountered while building the effective model for sg.test.spring.web.guide:sg-web-initial:1.0.0-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:aws-core:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:secretsmanager:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sns:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sqs:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jdbc:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-validation:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @

org.apache.maven.model.building.ModelBuildingException: 10 problems were encountered while building the effective model for sg.test.spring.web.guide:sg-web-initial:1.0.0-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:aws-core:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:secretsmanager:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sns:jar is missing. @
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:sqs:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jdbc:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-validation:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:498)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:440)
	at org.apache.maven.model.building.DefaultModelBuilder.Build(DefaultModelBuilder.java:430)
	at clojure.tools.deps.alpha.extensions.pom$read_model.invokeStatic(pom.clj:64)
	at clojure.tools.deps.alpha.extensions.pom$read_model.invoke(pom.clj:54)
	at clojure.tools.deps.alpha.extensions.pom$read_model_file.invokeStatic(pom.clj:69)
	at clojure.tools.deps.alpha.extensions.pom$read_model_file.invoke(pom.clj:67)
	at clojure.tools.deps.alpha.extensions.pom$eval1401$fn__1403.invoke(pom.clj:105)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$children_task__785$fn__787$fn__788.invoke(alpha.clj:403)
	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__502.invoke(concurrent.clj:34)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

#+end_src

To solve this, just add versions to all exports.
And then make sure you change all <scope>test</scope> to runtime.
** AWS tips
   Log insights query tips
   https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html

   Log pattern
   https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html

   Localstack setup
AWS_ACCESS_KEY_ID=DUMMY;AWS_SECRET_ACCESS_KEY=DUMMY;OOB_AWS_ENDPOINT_OVERRIDE=http://localhost:4566;AWS_REGION=eu-west-1;AWS_PROFILE=x
** Chrome
   https://flaviocopes.com/how-to-fix-chrome-rendering-issue/
** JIRA

   Wysiwyg debacle https://jira.atlassian.com/browse/JRACLOUD-72631

and temp solution:
   
   https://oodlefinance.atlassian.net/browse/XXXXX?oldIssueView=true
** IntelliJ

   Suppress warnings
   https://gist.github.com/vegaasen/157fbc6dce8545b7f12c
** Docker
   Way to have multiple containers interact
   https://github.com/palantir/docker-compose-rule

   https://stackoverflow.com/questions/64182352/can-testcontainers-join-existing-network


   Alternatives
   https://www.youtube.com/watch?v=LGNEG-t96eE
   Minikube: https://minikube.sigs.k8s.io/

   Minikube author https://matt-rickard.com/docker-desktop-alternatives/
** Mesos
   https://www.youtube.com/watch?v=fxJ7qnpFtrc

   Strangeloop
   https://www.youtube.com/watch?v=gVGZHzRjvo0

   Executor
   https://www.youtube.com/watch?v=tzaYXgnYKyQ
   https://blog.allegro.tech/2018/01/mesos_executor.html

   Aurora - Gears vs maze
   https://youtu.be/uSa6WZO_vCg?t=242
** Localstack
   https://docs.localstack.cloud/aws/apigatewayv2/
** AWS
*** Articles and how tos
    AWS CDK vs Terraform
    https://www.metosin.fi/blog/comparing-aws-cdk-and-terraform/

    websockets with api gateway
    https://tsh.io/blog/implementing-websocket-with-aws-lambda-and-api-gateway/
*** Installing and using CDK & SAM & Localstack & CDK local
    Getting started
    https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html
    npm install -g aws-cdk

    Your first app
    https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html
    (Skip this if dealing with existing app)
    
    Install aws-sam-cli (SAM)
    https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html
    See brew commands on page. (install takes a while)
    https://github.com/aws/aws-sam-cli

    Install Localstack
    https://docs.localstack.cloud/get-started/#localstack-cli
    Using pip as per instructions.
    After running 'localstack start' it takes a little while
    the logs to update.

    Install CDK local
    https://www.npmjs.com/package/aws-cdk-local

    Install AWS CLI
    https://formulae.brew.sh/formula/awscli
    brew install awscli

    Set up AWS account and configuring a profile.
    https://www.youtube.com/watch?v=2o6pY2DmVoo

    Install aws-local (wrapper around aws for localstack)
    https://github.com/localstack/awscli-local
    pip3 install awscli-loca
    
**** TODO Problems during brew install awscli
     https://github.com/Homebrew/homebrew-core/issues/100320
     
     #+begin_src
==> Pouring six--1.16.0_2.all.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink lib/python3.9/site-packages/six.py
Target /opt/homebrew/lib/python3.9/site-packages/six.py
already exists. You may want to remove it:
  rm '/opt/homebrew/lib/python3.9/site-packages/six.py'

To force the link and overwrite all conflicting files:
  brew link --overwrite six

To list all files that would be deleted:
  brew link --overwrite --dry-run six

Possible conflicting files are:
/opt/homebrew/lib/python3.9/site-packages/six.py
==> Summary
     #+end_src
**** DONE Unable to run cdklocal deploy or bootstrap
     CLOSED: [2022-04-28 Thu 16:24]
     This is solved by setting up an AWS and configuring a profile.
     
#+begin_src js
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at SdkProvider.resolveEnvironment (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:238:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at globEnvironmentsFromStacks (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/cxapp/environments.ts:19:20)
    at CdkToolkit.bootstrap (/opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:569:28)
    at initCommandLine (/opt/homebrew/lib/node_modules/aws-cdk/lib/cli.ts:341:12)
#+end_src
*** Lambda deployment and testing
Testing locally with localstack! Requires installation instructions in section above.
    https://www.youtube.com/watch?v=eszNbLXoaGQ

    Deploy and testing locally
#+begin_src bash
Deploy locally
sam local invoke -t cdk.out/***AwsDeployStack.template.json

cdklocal deploy
awslocal lambda invoke --function-name samsonBroker output.txt
#+end_src
**** DONE ERROR Not finding logs in localstack
     CLOSED: [2022-04-28 Thu 16:22]
     https://github.com/localstack/localstack/issues/2003
     https://stackoverflow.com/questions/55436251/aws-logs-the-specified-log-group-does-not-exist
 NOTE Error
 #+begin_src bash
   ;; Not necessary
   ;; export AWS_PROFILE=danielmarkgerson
   ;;
   
   awslocal logs tail /aws/lambda/
   
   An error occurred (ResourceNotFoundException) when calling the FilterLogEvents operation:
   The specified log group does not exist
 #+end_src

 Use the following to find the write name of the stack

 #+begin_src  bash
   awslocal logs describe-log-groups --endpoint-url http://localhost:4566
 #+end_src
 
*** Lambda comparison methods, further reading/viewing

Comparison
https://sanderknape.com/2018/02/comparing-aws-sam-with-serverless-framework/#:~:text=The%20biggest%20difference%20is%20that,creating%20a%20serverless%20HTTP%20endpoint.

    
https://github.com/aws-samples/simple-websockets-chat-app

*** SAM

    sam local start-api
    https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-start-api.html
    command reference and what happens behind the scenes.
    https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-api.html
    Understanding API gateway lambda integrations
    https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-create-api-as-simple-proxy
    

    SAM example and deployment
    https://youtu.be/MipjLaTp5nA?t=424
    - Understanding templates for type AWS::Serverless::Function lambdas (good description of considerations)
    

    Lambdas and SAM testing
    https://www.youtube.com/watch?v=AUQRyl1SNcU
    - sam local invoke -e
    - ApiGatewayFunction
    - docker in the background but this tutorial is only command line invoked.

    SAM with localstack
    https://stackoverflow.com/questions/60077552/how-to-deploy-sam-stack-with-localstack

    and SAM on same localstack network
    https://dev.to/vikasgarghb/sam-local-with-localstack-4285
    https://github.com/bilzard/aws-sam-localstack-example

    
   5 use cases
   https://www.youtube.com/watch?v=K-nnzpgrzwM
    
*** Serverless Framework (Alternative to CDK and cloudformation?)
    
    NPM https://www.npmjs.com/package/serverless-offline
    Github https://github.com/dherault/serverless-offline
    Tutorial https://www.youtube.com/watch?v=ul_85jfM0oo
    Youtube https://www.youtube.com/watch?v=dMVfqCTzuwk
