** Installing  mac

https://formulae.brew.sh/cask/emacs#default

brew install --cask emacs
Be mindful of https://github.com/syl20bnr/spacemacs/issues/12009
   
Clone spacemacs
https://www.spacemacs.org/#

#+begin_src 
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

ln -s ~/myconfig/spacemacs ~/.spacemacs
#+end_src

   https://emacs.stackexchange.com/questions/29096/how-to-sort-directories-first-in-dired
   brew install coreutils

#+begin_src
brew install --cask iterm2
brew install keepassx
brew install clojure
brew install --cask hammerspoon
#+end_src

https://github.com/peterklijn/hammerspoon-shiftit
   
** Installing spacemacs on windows
   
** Setting up the .spacemacs file  :windows:
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

You should use a hard link!


#+begin_src
git clone https://github.com/syl20bnr/spacemacs $home\AppData\Roaming\.emacs.d
#+end_src


Do the following from admin command line (Powershell doesn't work https://superuser.com/questions/1307360/how-do-you-create-a-new-symlink-in-windows-10-using-powershell-not-mklink-exe )
#+begin_src 
mklink C:\Users\PC\AppData\Roaming\.spacemacs C:\Users\PC\AppData\Roaming\myconfig\spacemacs
#+end_src


Soft links are as follows but we don't want that:
#+begin_src 
mklink /D Link Target
#+end_src
** Fixing a bug in projectile
If you get the following


 org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo

https://github.com/syl20bnr/spacemacs/issues/9374

#+begin_src 
find ~/.emacs.d/elpa -name "*elc" -delete
#+end_src
** SDKMAN on windows is more complicated.  :windows:
You need git bash which is probably already installed (to install spacemacs).
** Git auto pushing for mytracked files.

You need to register your email address in the git config if you haven't done so before.

#+begin_src 
PC@LAPTOP-74MHHK0F MINGW64 ~/mytrackedfiles (master)
$ git config --global user.name "dmg46664"

PC@LAPTOP-74MHHK0F MINGW64 ~/mytrackedfiles (master)
$ git config --global user.email "dmg46664@noreply.github.com"
#+end_src
** Clojure tools

https://clojure.org/guides/getting_started

Installed with the -bypass (see lower down in the windows guide) option and chose
location 1.

Maybe try scoop
https://scoop.sh/
There's also https://chocolatey.org/
https://dev.to/bowmanjd/chocolatey-vs-scoop-package-managers-for-windows-2kik

https://github.com/lukesampson/scoop/issues/4097

(Didn't have to install powershell or ndk

Had to turn off McAfee by Settings (top right icon) -> Off: Real time scanning, Firewall, 

#+begin_src 
PS C:\Users\PC> scoop install git
Checking repo... ok
The java bucket was added successfully.
PS C:\Users\PC> scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
Checking repo... ok
The scoop-clojure bucket was added successfully.
PS C:\Users\PC> scoop bucket add java
Checking repo... ok
The java bucket was added successfully.
PS C:\Users\PC> scoop install zulu13
Installing 'zulu13' (13.28.11) [64bit]
#+end_src

Got stuck on the last line and had to press enter
#+begin_src 
PS C:\Users\PC> scoop install zulu13
Installing 'zulu13' (13.28.11) [64bit]
...
Checking hash of zulu13.28.11-ca-jdk13.0.1-win_x64.zip ... ok.
#+end_src
** Zsh

https://github.com/romkatv/powerlevel10k

Some basics
https://scriptingosx.com/2019/06/moving-to-zsh-part-3-shell-options/

Tutorial
https://www.youtube.com/watch?v=eLEo4OQ-cuQ
brew install zsh-syntax-highlighting

writing completions
https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
More helpful
https://unix.stackexchange.com/questions/239528/dynamic-zsh-autocomplete-for-custom-commands
BB completions
https://github.com/babashka/babashka/wiki/Shell-completion

#+begin_src sh
fpath+=(~/.zsh_completions)
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
#+end_src
** iterm2
natural text editing
https://apple.stackexchange.com/a/293988/209569
** More scoop installs
https://github.com/lukesampson/scoop/issues/335
scoop bucket add extras
scoop install emacs
(hangs at the end and have to click enter)

When you load emacs on Windows, you'll likely get too many pipes/files
error each time you load it as it installs the libraries.
Just keep closing it and opening it until it loads.

scoop install keepass

# Note: if you get an error you might need to change the execution policy (i.e. enable Powershell) with
# Set-ExecutionPolicy RemoteSigned -scope CurrentUser
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
scoop bucket add extras
scoop install babashka

https://superuser.com/questions/361816/pass-command-line-arguments-to-windows-open-with

** Shell

https://hyper.is/#installation

** Drivers

https://www.instructables.com/How-to-Fix-Double-Press-Apostrophe-and-Quotes-in-W/
   
logitech.com/support/x56

New nvidia drivers
Geforce Experience

*** Bluetooth disconnection issue
 Dell drivers
 https://mail.google.com/mail/u/0/#search/dell/FMfcgzGkXwGgkltrGHNmhlFHmTqgCmQb


 Keychron issue?
 Bluetooth HID device  either went out of range or became unresponsive.
 https://www.reddit.com/r/Keychron/comments/hu60to/keychron_k2_v1_bluetooth_issues_i_give_up/

 Bluetooth waking up
 https://answers.microsoft.com/en-us/windows/forum/all/how-can-shutting-down-bluetooth-on-one-device/46917ef7-130e-4073-8094-0b002ea0e8b4

 Attempted to change power settings under Power and sleep.


 Killer Wi-Fi 6 AX1650x:
 Device Manager -> Killer Wi-Fi 6 AX1650x 160Mhz -> Power -> Allow the computer to turn off device to save power. (Disable)
 https://answers.microsoft.com/en-us/surface/forum/all/power-management-tab-is-missing-from-device/0a3c563a-5ec7-4809-9609-4bc257444590
 https://support.plugable.com/t/bluetooth-connections-being-broken-after-being-idle-presumably-due-to-power-management/19491/2

Error when installing latest drivers
 https://downloadcenter.intel.com/download/30581/Intel-Killer-Performance-Suite


 
** Utilities
   Clean up disk files https://dev.yorhel.nl/ncdu
   VPN https://tailscale.com/
